### ISSUE TITLE
Feature Request - Ability to control .d.ts extension

### ISSUE THREAD

**Issue by johlrich** [fable-compiler/Fable.Store#8]
Wow the d.ts generation is pretty great. The dx with fable + svelte + snowpack feels really smooth.

To keep things simple and not need any kind of resolving / aliasing, it would be great I could generate the .d.ts files with the same file name as the .js. So if Foo.fs is creating Foo.fs.js then I'd generate Foo.fs.d.ts to support an imports from Foo.fs.js directly.

It looks pretty easy to be configurable on the attribute, but I was hoping for something more global.

Happy to help if accepted

**Comment by alfonsogarciacaro** [comment]
Thanks @johlrich! Hmm, did you try to rename the files manually? IIRC I did try something like that at the beginning but it didn't work because Typescript didn't recognize the declaration if the JS import ended with .fs or .fs.js

**Comment by johlrich** [comment]
@alfonsogarciacaro Once renamed, the editor picks up the definition. Here's what I believe is happening:

I think the difference is because the existing samples rely on the additional tooling to allow imports without extensions via the webpack config. So something like `import { makeStore } from "./TodoMVC";` causes editor tooling to looking for `TodoMVC.d.ts`.

Since I don't setup anything special to work with .fs files my imports look like `import { makeStore } from "./TodoMVC.fs.js";`, which I think causes the editor tooling to search for `TodoMVC.fs.d.ts`. Snowpack is configured to ignore .fs and just runs fable.

**Comment by alfonsogarciacaro** [comment]
Weird. it's not working for me. If I change the extension of the .d.ts and the import, the editor stops type checking it 😕 

![image](https://user-images.githubusercontent.com/8275461/108178442-c9f7a980-7147-11eb-9958-b3402d83c61b.png)

**Comment by johlrich** [comment]
Try running "Svelte: Restart Language Server" from the VS Code Command Palette after renaming the .d.ts file. Here's what mine looks like shortly after:

![image](https://user-images.githubusercontent.com/1655793/108180899-4309e900-70d5-11eb-9be1-de6b4dd5d3ec.png)

**Comment by alfonsogarciacaro** [comment]
Ah, ok! Now it's working, this was confusing 😅 So... should we just use `.fs.d.ts` extension as default and remove the recommendation to use the `resolve` Webpack option from the README? Or keep it as is and make the extension of the declaration configurable? ...hmm, if there are not many users of the plugin yet, maybe the first option is simpler, what do you think?

**Comment by johlrich** [comment]
I think the `.fs.d.ts` being the default makes the most sense. There would be one less thing to configure and makes the svelte samples closer to the existing interop approach from the fable3-samples repo.

https://github.com/fable-compiler/fable3-samples/blob/19840b7f00f32ba189c73a7a2f7be8f52e6743f6/interopFableFromJS/src/index.js#L1

The only additional consideration would be around the usage of `--extension`. If someone uses `--extension .js` then they likely want plain `.d.ts` to match.

**Comment by johlrich** [comment]
Regarding the extension option, I just noticed the option is available in the transform via the `PluginHelper`. I did not test this yet, but I think something like this would cover default and extension usage. What do you think?

```fs
        let typesExtension = Regex.Replace(h.Options.FileExtension, "\.js$", ".d.ts")
        let path = Regex.Replace(h.CurrentFile, "\.fs$", typesExtension)
```

**Comment by alfonsogarciacaro** [comment]
I forgot about that 😅 That's a great idea! I've published a new version with the change 👍
